language: ruby
sudo: false
cache: bundler
script: bundle exec rake spec
bundler_args: --without development
rvm:
  - jruby
  - jruby-head
jdk:
  - openjdk7
matrix:
  allow_failures:
    - rvm: jruby-head
  fast_finish: true
